# Generated by Django 5.2.1 on 2026-07-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncsource',
            name='is_syncing',
        ),
    ]
