# Generated by Django 5.2.1 on 2026-07-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_block_explicit_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='not_loaded', max_length=20)),
                ('playlist_offset', models.PositiveIntegerField(default=0)),
                ('credits_executed', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.programme')),
            ],
        ),
    ]
