# Generated by Django 5.2.1 on 2026-07-03 23:13

import django.db.models.deletion
from django.db import migrations, models


def mark_command_programmes_stale(apps, schema_editor):
    """
    Command blocks change playlist shape under the new cue rules (instant
    commands no longer emit a black.mp4 playlist item), so force a rebuild
    the next time each affected programme is loaded.
    """
    Programme = apps.get_model("api", "Programme")
    Programme.objects.filter(blocks__content_type="command").distinct().update(playlist_stale=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_command_provider_refit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='preshow_command',
        ),
        migrations.AddField(
            model_name='playoutsession',
            name='programme_cursor',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='programmeblock',
            name='hold_black',
            field=models.BooleanField(default=False, help_text="Show a black screen for the command's duration while it runs"),
        ),
        migrations.AddField(
            model_name='programmetemplateitem',
            name='hold_black',
            field=models.BooleanField(default=False, help_text="Show a black screen for the command's duration while it runs"),
        ),
        migrations.CreateModel(
            name='PlaylistCue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(blank=True, default='', max_length=255)),
                ('fires_before_order', models.PositiveIntegerField()),
                ('seq', models.PositiveIntegerField(default=0)),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.command')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cues', to='api.playlist')),
            ],
            options={
                'ordering': ['fires_before_order', 'seq'],
            },
        ),
        migrations.RunPython(mark_command_programmes_stale, migrations.RunPython.noop),
    ]
