# Generated by Django 5.2.1 on 2026-07-14 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_programme_preshow_command_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(blank=True, default='', max_length=10)),
                ('ticket_number', models.PositiveIntegerField(db_index=True, help_text='Global running ticket counter')),
                ('kind', models.CharField(choices=[('movie', 'Movie'), ('programme', 'Programme'), ('custom', 'Custom')], max_length=12)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('printed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_issues', to='api.movie')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_issues', to='api.programme')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_issues', to='api.programmeschedule')),
            ],
            options={
                'ordering': ['-printed_at', '-id'],
            },
        ),
    ]
