# Generated by Django 5.2.16 on 2026-07-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ticketissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='last_played_at',
            field=models.DateTimeField(blank=True, help_text='When playback of this programme last started', null=True),
        ),
    ]
