# Generated by Django 5.2.16 on 2026-08-04 15:50
#
# Per-system certificate storage (issue #148): adds the `certificates` /
# `rating_lookups` JSON stores to Movie and Trailer, makes Certification
# cards system-aware, seeds them from the legacy scalar fields, and retires
# the BBFC-specific bits (Trailer.bbfcmatch, trailers.bbfc_* settings).

from django.db import migrations, models

VALID_SYSTEMS = ("BBFC", "MPAA")


def _configured_system(settings_model):
    """The ratings system configured at migration time (default BBFC)."""
    row = settings_model.objects.filter(id=1).first()
    if not row:
        return "BBFC"
    system = (row.data or {}).get("cinema", {}).get("ratings_system", "BBFC")
    return system if system in VALID_SYSTEMS else "BBFC"


def seed_per_system_data(apps, schema_editor):
    Settings = apps.get_model("api", "Settings")
    Movie = apps.get_model("api", "Movie")
    Trailer = apps.get_model("api", "Trailer")
    Certification = apps.get_model("api", "Certification")

    system = _configured_system(Settings)

    # Legacy scalar certificates belong to whichever system was configured
    # when they were fetched — i.e. the one configured now.
    for movie in Movie.objects.exclude(certification=""):
        movie.certificates = {system: movie.certification}
        movie.save(update_fields=["certificates"])

    for trailer in Trailer.objects.all():
        changed = []
        if trailer.content_rating:
            trailer.certificates = {system: trailer.content_rating}
            changed.append("certificates")
        # bbfcmatch yes/no → a BBFC lookup marker (lookups were BBFC-only).
        if trailer.bbfcmatch in ("yes", "no"):
            trailer.rating_lookups = {"BBFC": "matched" if trailer.bbfcmatch == "yes" else "unmatched"}
            changed.append("rating_lookups")
        if changed:
            trailer.save(update_fields=changed)

    # Existing generated cards used the configured system's backgrounds.
    Certification.objects.update(ratings_system=system)

    # Settings: trailers.bbfc_enabled → trailers.rating_lookup_enabled;
    # trailers.bbfc_api_url is gone (lookups no longer use an external service).
    row = Settings.objects.filter(id=1).first()
    if row:
        trailers = (row.data or {}).get("trailers")
        if isinstance(trailers, dict):
            if "rating_lookup_enabled" not in trailers:
                trailers["rating_lookup_enabled"] = trailers.get("bbfc_enabled", True)
            trailers.pop("bbfc_enabled", None)
            trailers.pop("bbfc_api_url", None)
            row.save(update_fields=["data"])


def unseed_per_system_data(apps, schema_editor):
    """Reverse: restore bbfcmatch and the bbfc_enabled settings key."""
    Settings = apps.get_model("api", "Settings")
    Trailer = apps.get_model("api", "Trailer")

    for trailer in Trailer.objects.all():
        marker = (trailer.rating_lookups or {}).get("BBFC", "")
        if marker in ("matched", "unmatched"):
            trailer.bbfcmatch = "yes" if marker == "matched" else "no"
            trailer.save(update_fields=["bbfcmatch"])

    row = Settings.objects.filter(id=1).first()
    if row:
        trailers = (row.data or {}).get("trailers")
        if isinstance(trailers, dict) and "rating_lookup_enabled" in trailers:
            trailers["bbfc_enabled"] = trailers.pop("rating_lookup_enabled")
            row.save(update_fields=["data"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_programme_last_played_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="ratings_system",
            field=models.CharField(default="BBFC", max_length=10),
        ),
        migrations.AddField(
            model_name="movie",
            name="certificates",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating_lookups",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="trailer",
            name="certificates",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="trailer",
            name="rating_lookups",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(seed_per_system_data, unseed_per_system_data),
        migrations.RemoveField(
            model_name="trailer",
            name="bbfcmatch",
        ),
    ]
