# Generated by Django 5.2.16 on 2026-08-08 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_trailer_bbfcmatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmetemplateitem',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trailer'),
        ),
        migrations.AlterField(
            model_name='programmetemplateitem',
            name='item_type',
            field=models.CharField(choices=[('command', 'Command'), ('bumper', 'Bumper'), ('trailer', 'Trailer'), ('feature', 'Feature Film'), ('trailer_rule', 'Trailer Rule'), ('certification', 'Certification (auto)'), ('random_bumper', 'Random Bumper by Tag'), ('audio_bumper', 'Audio Bumper')], max_length=20),
        ),
    ]
