# Generated by Django 5.2.16 on 2026-08-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_programmetemplateitem_trailer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncsource",
            name="url",
            field=models.CharField(
                help_text="Server URL (e.g. http://192.0.2.10:32400)", max_length=500
            ),
        ),
    ]
