# Generated by Django 5.2.16 on 2026-08-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_syncsource_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="dry_run",
        ),
        migrations.RemoveField(
            model_name="job",
            name="plan",
        ),
    ]
