# Generated by Django 5.2.16 on 2026-08-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_job_dry_run_remove_job_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistitem",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
