# Generated by Django 5.2.16 on 2026-08-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_playlistitem_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="plex_rating_key",
            field=models.CharField(
                blank=True, default="", help_text="Plex ratingKey", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="remote_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Server-side updatedAt at last sync (incremental change detection)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="syncsource",
            name="path_mappings",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Path rewrites: [{"from": "/server/path", "to": "/local/path"}]',
            ),
        ),
        migrations.AlterField(
            model_name="syncsource",
            name="sync_type",
            field=models.CharField(
                choices=[("plex", "Plex Media Server"), ("jellyfin", "Jellyfin")],
                max_length=20,
            ),
        ),
    ]
