# Generated by Django 5.2.16 on 2026-08-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_movie_plex_rating_key_movie_remote_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bumper",
            name="is_uploaded",
        ),
    ]
