# Generated by Django 5.2.16 on 2026-08-15 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_bumper_is_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='programmeblock',
            name='trailer_tag',
            field=models.ForeignKey(blank=True, help_text='Only pick trailers carrying this tag (bound trailer rules)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.trailertag'),
        ),
        migrations.AddField(
            model_name='programmetemplateitem',
            name='trailer_tag',
            field=models.ForeignKey(blank=True, help_text='Only pick trailers carrying this tag (trailer rules)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.trailertag'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='trailer_tags',
            field=models.ManyToManyField(blank=True, related_name='trailers', to='api.trailertag'),
        ),
        migrations.AddField(
            model_name='trailerrule',
            name='trailer_tag',
            field=models.ForeignKey(blank=True, help_text='Only pick trailers carrying this tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.trailertag'),
        ),
    ]
