# Generated by Django 5.2.16 on 2026-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_trailertag_programmeblock_trailer_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoutHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the playout host', max_length=255)),
                ('base_url', models.CharField(default='http://127.0.0.1:8089', help_text='Agent HTTP base URL, e.g. http://127.0.0.1:8089', max_length=500)),
                ('token', models.CharField(blank=True, default='', help_text='Bearer token for the agent', max_length=500)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this host may be used for playout')),
                ('is_active', models.BooleanField(default=False, help_text='The single host used for playout (exactly one row is active)')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last successful agent contact', null=True)),
                ('agent_version', models.CharField(blank=True, default='', max_length=100)),
                ('os', models.CharField(blank=True, default='', max_length=50)),
                ('arch', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
