# Generated by Django 5.2.16 on 2026-08-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_seed_playout_host"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human label, e.g. 'Home Assistant'", max_length=100
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        help_text="Display prefix, e.g. cplx_a1b2c3d4", max_length=32
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
