# Generated by Django 5.2.16 on 2026-08-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_api_keys"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programme",
            name="stream_programme",
        ),
    ]
