# Generated by Django 5.2.16 on 2026-09-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_remove_programme_stream_programme"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("elements", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="programme",
            name="ticket_design",
            field=models.ForeignKey(
                blank=True,
                help_text="Ticket design for this programme's tickets (blank = the default design)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programmes",
                to="api.ticketdesign",
            ),
        ),
    ]
