# Generated by Django 6.1 on 2026-09-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_movie_poster_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='playouthost',
            name='kind',
            field=models.CharField(choices=[('agent', 'Playout agent (WebSocket)'), ('local_socket', 'Local mpv (JSON-IPC socket)')], default='agent', help_text='Transport: remote agent (WebSocket) or a local mpv JSON-IPC socket', max_length=20),
        ),
        migrations.AddField(
            model_name='playouthost',
            name='socket_path',
            field=models.CharField(blank=True, default='', help_text='mpv --input-ipc-server path, e.g. /tmp/mpvsocket (local_socket kind only)', max_length=500),
        ),
        migrations.AlterField(
            model_name='playouthost',
            name='base_url',
            field=models.CharField(default='http://127.0.0.1:8089', help_text='Agent HTTP base URL, e.g. http://127.0.0.1:8089 (agent kind only)', max_length=500),
        ),
    ]
