# Generated by Django 6.1 on 2026-09-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_single_library_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailerrule',
            name='match_certification',
        ),
        migrations.RemoveField(
            model_name='trailerrule',
            name='match_genres',
        ),
        migrations.RemoveField(
            model_name='trailerrule',
            name='year_delta',
        ),
        migrations.AddField(
            model_name='trailerrule',
            name='certificate_ceiling',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='trailerrule',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='+', to='api.genre'),
        ),
        migrations.AddField(
            model_name='trailerrule',
            name='year_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailerrule',
            name='year_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailerrule',
            name='reference_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailer_rules', to='api.movie'),
        ),
    ]
