# Generated by Django 6.1 on 2026-09-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_trailerrule_match_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_bitrate',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_codec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_framerate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
