# Generated by Django 6.1 on 2026-09-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_movie_video_bitrate_movie_video_codec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='content_type',
            field=models.CharField(blank=True, choices=[('movie', 'MoviePlayback'), ('bumper', 'Bumper'), ('command', 'Command'), ('certification', 'Certification'), ('trailer', 'Trailer'), ('system', 'System')], max_length=20),
        ),
    ]
