# Generated by Django 6.1 on 2026-09-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_alter_playlistitem_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncschedule",
            name="operation",
            field=models.CharField(default="sync", help_text='Operation to run (currently only "sync")', max_length=40),
        ),
    ]
