# Generated by Django 6.1 on 2026-09-19 21:15

import django.db.models.deletion
from django.db import migrations, models


def merge_random_bumper_into_bumper(apps, schema_editor):
    """Merge the retired "random_bumper" type into "bumper".

    A "bumper" (User Media) block/item is now either a specific clip or a
    random pick from a tag — a tag set means random. Every legacy row that
    carried the separate "random_bumper" type already stores its tag/count on
    the row (ProgrammeBlock.random_tag/random_count, ProgrammeTemplateItem.tag/
    count), so the conversion is a straight rename of the type string.
    """
    ProgrammeBlock = apps.get_model("api", "ProgrammeBlock")
    ProgrammeTemplateItem = apps.get_model("api", "ProgrammeTemplateItem")

    ProgrammeBlock.objects.filter(content_type="random_bumper").update(content_type="bumper")
    ProgrammeTemplateItem.objects.filter(item_type="random_bumper").update(item_type="bumper")


def split_bumper_back_to_random_bumper(apps, schema_editor):
    """Reverse: send tag-carrying "bumper" rows back to "random_bumper"."""
    ProgrammeBlock = apps.get_model("api", "ProgrammeBlock")
    ProgrammeTemplateItem = apps.get_model("api", "ProgrammeTemplateItem")

    ProgrammeBlock.objects.filter(content_type="bumper", random_tag__isnull=False).update(content_type="random_bumper")
    ProgrammeTemplateItem.objects.filter(item_type="bumper", tag__isnull=False).update(item_type="random_bumper")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_alter_syncschedule_operation"),
    ]

    operations = [
        # Convert legacy rows before the choices tighten (choices aren't a DB
        # constraint under SQLite, so this is for data cleanliness/consistency).
        migrations.RunPython(merge_random_bumper_into_bumper, split_bumper_back_to_random_bumper),
        migrations.AlterField(
            model_name="programmeblock",
            name="content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("movie", "Movie"),
                    ("bumper", "User Media"),
                    ("command", "Command"),
                    ("trailer_rule", "Trailer Rule"),
                    ("certification", "Certification"),
                    ("trailer", "Trailer"),
                    ("random_movie", "Random Movie"),
                    ("audio_bumper", "Audio Bumper"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="programmetemplateitem",
            name="count",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of random items to select (when a tag is set)"
            ),
        ),
        migrations.AlterField(
            model_name="programmetemplateitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("command", "Command"),
                    ("bumper", "User Media"),
                    ("trailer", "Trailer"),
                    ("feature", "Feature Film"),
                    ("trailer_rule", "Trailer Rule"),
                    ("certification", "Certification (auto)"),
                    ("audio_bumper", "Audio Bumper"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="programmetemplateitem",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                help_text="For random user-media selection",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.tag",
            ),
        ),
    ]
