# Generated by Django 6.1 on 2026-09-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_programmeblock_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Optional badge colour as #RRGGBB (blank = neutral)', max_length=7),
        ),
    ]
