# Generated by Django 6.1 on 2026-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_relativise_media_paths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="provider",
            field=models.CharField(default="rest", max_length=40),
        ),
    ]
