# Generated by Django 6.1 on 2026-09-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_move_homeassistant_settings_to_plugins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='SyncSchedule',
        ),
    ]
