# Generated by Django 6.1.1 on 2026-09-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_preshow_cue_lead_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeschedule',
            name='lead_in',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds before the programme plays; null = the scheduler.lead_in default', null=True),
        ),
    ]
