# Generated by Django 6.1.1 on 2026-09-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_programmeschedule_lead_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='title_hold',
            field=models.BooleanField(default=False, help_text="When cued, play the title's fade-in, then hold"),
        ),
    ]
