# Generated by Django 6.1.1 on 2026-09-26 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_programme_title_hold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='title_duration',
        ),
    ]
