# Generated by Django 6.1.1 on 2026-09-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_programme_title_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='show_on_remote',
        ),
    ]
