# Generated by Django 6.1.1 on 2026-09-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_per_screening_lead_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncsource',
            name='libraries',
            field=models.TextField(default='Movies', help_text='Comma-separated list of library names to sync'),
        ),
    ]
