# Generated by Django 6.1.1 on 2026-09-28 15:59

from django.db import migrations, models


def drop_unused_seed_host(apps, schema_editor):
    """Remove 0019's placeholder host if nobody ever set it up.

    Agents are now added by pairing, so an inactive loopback row with no token
    can never be used, and on a fresh install it would hide the pairing screen.
    A row anyone touched (renamed, re-pointed, given a token, activated) stays.
    """
    PlayoutHost = apps.get_model("api", "PlayoutHost")
    PlayoutHost.objects.filter(
        name="Playout host", base_url="http://127.0.0.1:8089", token="", is_active=False, kind="agent"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_syncsource_libraries'),
    ]

    operations = [
        migrations.AddField(
            model_name='playouthost',
            name='agent_id',
            field=models.CharField(blank=True, default='', help_text="The agent's stable id (from pairing / mDNS), to recognise it when its address changes", max_length=64),
        ),
        migrations.AlterField(
            model_name='playouthost',
            name='token',
            field=models.CharField(blank=True, default='', help_text='Bearer token the agent issued when it was paired', max_length=500),
        ),
        migrations.RunPython(drop_unused_seed_host, migrations.RunPython.noop),
    ]
