# Generated by Django 6.1.1 on 2026-09-30 20:44

import django.core.validators
from django.db import migrations, models


def rename_reset_command(apps, schema_editor):
    """The system plugin's "Reset to the idle ident" built-in is now "Standby".

    Built-ins are matched by their config, so update the existing row in place
    (keeping its id, duration and every lead-in or block that uses it) before
    the post-migrate step would add a second one.
    """
    Command = apps.get_model("api", "Command")
    for command in Command.objects.filter(provider="system"):
        if (command.config or {}).get("action") == "Reset to the idle ident":
            command.name = "Standby"
            command.config = {"action": "Standby"}
            command.save(update_fields=["name", "config"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_playouthost_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bumper',
            name='hold_point',
            field=models.FloatField(blank=True, help_text='As the ident: where standby freezes, in seconds (empty = its last frame)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='playouthost',
            name='protocol',
            field=models.PositiveSmallIntegerField(default=0, help_text="The agent's protocol version, from pairing and refresh (0 = unknown)"),
        ),
        migrations.AddField(
            model_name='playouthost',
            name='show_status',
            field=models.BooleanField(default=True, help_text='Whether the player shows its status (names, link state) over standby'),
        ),
        migrations.RunPython(rename_reset_command, migrations.RunPython.noop),
    ]
