# Generated by Django 6.1.1 on 2026-10-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_ticket_element_widths'),
    ]

    operations = [
        migrations.AddField(
            model_name='playouthost',
            name='min_protocol',
            field=models.PositiveSmallIntegerField(default=0, help_text='The oldest Cinefin protocol the agent still serves, from pairing and refresh (0 = any)'),
        ),
    ]
