# Generated by Django 6.1.1 on 2026-10-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_ticket_element_widths'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoutsession',
            name='manual_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
