# Generated by Django 6.1.1 on 2026-10-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_playout_session_manual_items'),
        ('api', '0053_playouthost_min_protocol'),
    ]

    operations = [
    ]
