# Generated by Django 6.1.1 on 2026-10-03 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_merge_playout_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='playouthost',
            name='access_url',
            field=models.CharField(blank=True, default='', help_text="The Cinefin URL last sent to the player with its key ('' = never sent)", max_length=500),
        ),
        migrations.AddField(
            model_name='playouthost',
            name='api_key',
            field=models.ForeignKey(blank=True, help_text='The key the player calls Cinefin with; revoking it on the Security page keeps it revoked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.apikey'),
        ),
        migrations.AddField(
            model_name='playouthost',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text="What the agent offers beyond playout, from pairing and refresh (e.g. 'browse')"),
        ),
    ]
