"""
Django settings for cinefin project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import logging
import os
from pathlib import Path

from django.urls import reverse_lazy

# BASE_DIR is the backend/ directory (the Python project root — holds the
# `cinefin` package, manage.py and pyproject.toml). REPO_ROOT is one level up,
# the repository root that also holds the sibling frontend/ and the runtime
# data dirs (usermedia/, db.sqlite3, logs/). Use BASE_DIR for code assets under
# cinefin/, REPO_ROOT for everything alongside the backend.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BASE_DIR.parent

# One directory holds ALL runtime data: the SQLite db, user media (MEDIA_ROOT →
# userdata/media), the persisted SECRET_KEY and, when enabled, the logfile. Point
# CINEFIN_USERDATA_DIR at a mounted volume to relocate the lot; the per-item paths
# below (SQLITE_PATH, CINEFIN_USERMEDIA_DIR, …) still override individually.
CINEFIN_USERDATA_DIR = os.environ.get("CINEFIN_USERDATA_DIR") or str(REPO_ROOT / "userdata")

LOGIN_URL = reverse_lazy("login")
LOGIN_REDIRECT_URL = "/app/"
LOGOUT_REDIRECT_URL = "/app/"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


def _load_or_create_secret_key() -> str:
    """
    The Django SECRET_KEY: the SECRET_KEY env var when set, otherwise a key
    generated on first run and persisted at CINEFIN_SECRET_KEY_FILE (default
    userdata/.secret_key). It lives with the rest of the runtime data so a
    backup/restore of the userdata dir keeps every session valid. Falls back to
    an ephemeral key — logged loudly — if the path is unwritable.
    """
    from_env = os.environ.get("SECRET_KEY")
    if from_env:
        return from_env
    from django.core.management.utils import get_random_secret_key

    key_file = Path(os.environ.get("CINEFIN_SECRET_KEY_FILE") or os.path.join(CINEFIN_USERDATA_DIR, ".secret_key"))
    try:
        if key_file.exists():
            stored = key_file.read_text().strip()
            if stored:
                return stored
        key_file.parent.mkdir(parents=True, exist_ok=True)
        generated = get_random_secret_key()
        key_file.write_text(generated)
        os.chmod(key_file, 0o600)
        return generated
    except OSError as exc:
        logging.getLogger("cinefin").warning(
            "Could not persist SECRET_KEY at %s (%s) — using an ephemeral key; sessions "
            "will reset every restart. Set the SECRET_KEY env var to a fixed value.",
            key_file,
            exc,
        )
        return get_random_secret_key()


SECRET_KEY = _load_or_create_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
# Default OFF: the systemd deployment leaves CINEFIN_DEBUG unset. Set
# CINEFIN_DEBUG=1 for local development (Docker uses its own DEBUG env var,
# see settings_docker.py).
DEBUG = os.environ.get("CINEFIN_DEBUG", "0") == "1"

# Accept any Host header by default — a single-user home box, typically behind no
# proxy on a trusted LAN. Restrict it with CINEFIN_ALLOWED_HOSTS=host1,host2 (an
# explicit list replaces the wildcard).
_allowed_hosts = [h.strip() for h in os.environ.get("CINEFIN_ALLOWED_HOSTS", "").split(",") if h.strip()]
ALLOWED_HOSTS = _allowed_hosts or ["*"]

# When Cinefin runs behind a reverse proxy, REMOTE_ADDR is the proxy's IP, so
# the login brute-force lockout would key on it and lock everyone out at once.
# Set CINEFIN_TRUST_PROXY=1 ONLY when a trusted proxy sets X-Forwarded-For, so
# the real client IP is used instead. Off by default (the header is
# client-spoofable, so trusting it without a proxy in front would let an
# attacker evade the lockout).
CINEFIN_TRUST_PROXY = os.environ.get("CINEFIN_TRUST_PROXY", "0") == "1"

# Cinefin server URL for streaming - used to build absolute URLs for playlist items
CINEFIN_SERVER_URL = os.environ.get("CINEFIN_SERVER_URL", "http://localhost:8000")

# Skip the background worker threads (sync engine, schedule runner) and the
# boot-time media-tree creation. The test suite sets this (test_settings), and a
# build-time django.setup() (e.g. PyInstaller freezing) sets the env var so
# importing the project has no side effects.
CINEFIN_DISABLE_BACKGROUND_WORKERS = os.environ.get("CINEFIN_DISABLE_BACKGROUND_WORKERS") == "1"

# Where the "update available" check looks for the latest release.
# CINEFIN_UPDATE_HOST is the forge base URL (GitHub and Gitea are both
# understood — see version_check_service); CINEFIN_UPDATE_REPO is the
# owner/repo slug. Together they build the releases/latest API endpoint. Both
# are overridable via the environment; the check is best-effort and never
# surfaces a network error to the user.
CINEFIN_UPDATE_HOST = os.environ.get("CINEFIN_UPDATE_HOST", "https://github.com").rstrip("/")
CINEFIN_UPDATE_REPO = os.environ.get("CINEFIN_UPDATE_REPO", "cinefin/cinefin").strip("/")

# Application version — resolved from the CINEFIN_VERSION env (set in the Docker
# image) or `git describe`. See cinefin/version.py for the single source of truth.
from cinefin.version import get_version as _get_version  # noqa: E402

CINEFIN_VERSION = _get_version()

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cinefin.api",
]

# Application log level (the "cinefin" logger tree). INFO by default; set
# CINEFIN_LOG_LEVEL=DEBUG in the environment to get playback/event chatter.
CINEFIN_LOG_LEVEL = os.environ.get("CINEFIN_LOG_LEVEL", "INFO").upper()

# uvicorn's access log is one line per HTTP request — pure noise on a home box
# where the SPA polls status endpoints every second. Silenced by default; set
# CINEFIN_ACCESS_LOG=1 to restore it (routed through our handlers, so the in-app
# log viewer catches it too). The pip/Windows launcher honours the same var
# directly via uvicorn's access_log flag (see cli.py).
CINEFIN_ACCESS_LOG = os.environ.get("CINEFIN_ACCESS_LOG") == "1"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        # In-memory ring buffer backing the in-app log viewer
        # (GET /api/v2/logs). See cinefin/log_buffer.py.
        "ringbuffer": {
            "level": "DEBUG",
            "class": "cinefin.log_buffer.BufferHandler",
        },
    },
    # Catch-all so loggers outside the trees below (orphan third-party
    # loggers) still surface — at WARNING and above only.
    "root": {
        "handlers": ["console", "ringbuffer"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "ringbuffer"],
            "level": "INFO",
            "propagate": False,  # has its own handlers; don't double-log via root
        },
        "cinefin": {
            "handlers": ["console", "ringbuffer"],
            "level": CINEFIN_LOG_LEVEL,
            "propagate": False,
        },
        # Third-party chatter: only WARNING and above (propagates to root).
        "plexapi": {"level": "WARNING"},
        "urllib3": {"level": "WARNING"},
        "yt_dlp": {"level": "WARNING"},
        # Per-request access log — off by default (see CINEFIN_ACCESS_LOG above).
        "uvicorn.access": {
            "handlers": ["console", "ringbuffer"] if CINEFIN_ACCESS_LOG else [],
            "level": "INFO" if CINEFIN_ACCESS_LOG else "WARNING",
            "propagate": False,
        },
    },
}

# Opt-in logfile: set CINEFIN_LOG_FILE to a path (e.g. userdata/logs/cinefin.log)
# to also write logs there, size-rotated (5 MB × 5). Off by default — the console
# handler is enough under Docker/systemd, which capture stdout themselves.
CINEFIN_LOG_FILE = os.environ.get("CINEFIN_LOG_FILE")
if CINEFIN_LOG_FILE:
    Path(CINEFIN_LOG_FILE).parent.mkdir(parents=True, exist_ok=True)
    LOGGING["handlers"]["file"] = {
        "level": "DEBUG",
        "class": "logging.handlers.RotatingFileHandler",
        "filename": CINEFIN_LOG_FILE,
        "maxBytes": 5 * 1024 * 1024,
        "backupCount": 5,
        "formatter": "verbose",
    }
    for _target in (LOGGING["root"], LOGGING["loggers"]["django"], LOGGING["loggers"]["cinefin"]):
        _target["handlers"] = [*_target["handlers"], "file"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "cinefin.middleware.InstallerRedirectMiddleware",
    # Optional auth gate (security.auth_enabled). Placed AFTER
    # AuthenticationMiddleware (it reads request.user) and AFTER the installer
    # redirect (an unconfigured box is sent to setup before auth is considered).
    "cinefin.middleware.AuthGateMiddleware",
]

ROOT_URLCONF = "cinefin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["cinefin/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cinefin.context_processors.cinema_config",
            ],
        },
    },
]

WSGI_APPLICATION = "cinefin.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Ensure the db's parent (the userdata dir) exists before SQLite opens it —
# Django creates the file but not the directory.
_sqlite_path = os.environ.get("SQLITE_PATH") or os.path.join(CINEFIN_USERDATA_DIR, "db.sqlite3")
os.makedirs(os.path.dirname(_sqlite_path), exist_ok=True)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": _sqlite_path,
        # SQLite tuning for bulk imports + a concurrently-polled web UI.
        # WAL keeps a single reused -wal file instead of creating/deleting a
        # rollback journal on every insert, so bulk syncs are faster and far
        # less prone to "unable to open database file" (SQLITE_CANTOPEN) under
        # file-descriptor pressure. IMMEDIATE takes the write lock up front so
        # atomic blocks don't fail a lock upgrade mid-transaction, and the long
        # busy timeout lets readers (status poll, SSE log) and the writer wait
        # for each other instead of erroring.
        "OPTIONS": {
            "timeout": 30,
            "transaction_mode": "IMMEDIATE",
            "init_command": ("PRAGMA journal_mode=WAL;PRAGMA synchronous=NORMAL;PRAGMA busy_timeout=30000;"),
        },
    }
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = 200000

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, "cinefin", "staticfiles")
STATIC_URL = "/static/"

# Static serving is WhiteNoise in every deployment. Two deliberate choices so
# a box where `collectstatic` has never run (the systemd runserver deployment)
# cannot break with DEBUG off:
#
# * Non-manifest storage (CompressedStaticFilesStorage). The manifest variant
#   raises for every {% static %} reference missing from staticfiles.json —
#   i.e. 500s on every page when collectstatic never ran. (Note: the old
#   `STATICFILES_STORAGE = ...CompressedManifestStaticFilesStorage` setting
#   was silently ignored on Django >= 5.1 anyway; STORAGES is the supported
#   form, so manifest storage was never actually in effect.)
# * WHITENOISE_USE_FINDERS: serve straight from the app's static/ dirs via the
#   staticfiles finders, so STATIC_ROOT doesn't need to exist at all. Where a
#   collectstatic output does exist (the Docker image builds one) it is still
#   used and compressed as usual.
# * WHITENOISE_AUTOREFRESH: always on. Its default is settings.DEBUG, and with
#   DEBUG off WhiteNoise caches every file's size at startup — a git pull (or
#   any edit) that changes a JS file while the server runs is then served
#   TRUNCATED to its old Content-Length, silently killing that page's script.
#   Per-request stat calls are irrelevant at this app's scale; correctness on
#   pull-based deploys is not.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

STATICFILES_DIRS = (os.path.join(BASE_DIR, "cinefin", "static"),)


# Media files (uploaded/generated files like thumbnails)
MEDIA_URL = "/media/"
# The user-media directory (uploads, screenshots, generated cards, the trailer
# tree): userdata/media by default. Media resolves against this at runtime rather
# than baking an absolute path into the database. CINEFIN_USERMEDIA_DIR overrides
# it independently of the rest of the userdata dir.
MEDIA_ROOT = os.environ.get("CINEFIN_USERMEDIA_DIR") or os.path.join(CINEFIN_USERDATA_DIR, "media")

# Bundled app assets (rating card backgrounds, the system black clip, card
# branding). Tracked in the repo and shipped with the app — distinct from
# static/ (web-served) and MEDIA_ROOT (user data, may be a mounted volume).
# Env override lets a frozen/packaged build (e.g. the Windows bundle) point at
# its own extracted location instead of the source-tree-relative default.
CINEFIN_ASSETS_DIR = os.environ.get("CINEFIN_ASSETS_DIR") or os.path.join(BASE_DIR, "cinefin", "assets")

# The SvelteKit SPA build (frontend/, `npm run build:spa`), mounted at /app/ —
# THE UI. Served by cinefin.views.spa_view (index.html fallback + build
# assets) — WhiteNoise's Django integration can only mount trees under
# STATIC_URL, and the Kit build references its assets at the absolute
# /app/_app/… paths, so a plain Django view is the single serving point (the
# same trade-off the /media/ routes make; see urls.py). The directory is
# gitignored: without a build, /app/ answers 404 with a how-to-build hint.
FRONTEND_BUILD_DIR = os.environ.get("CINEFIN_FRONTEND_BUILD_DIR") or os.path.join(REPO_ROOT, "frontend", "build")

# Contrib command-provider plugins dir. Unset (None) → plugins.plugins_dir()
# falls back to REPO_ROOT/contrib/plugins (dev). A frozen build points this at
# its bundled copy.
CINEFIN_PLUGINS_DIR = os.environ.get("CINEFIN_PLUGINS_DIR") or None

# Thumbnail-specific settings

# The UI is served same-origin, so no cross-origin API access is needed by
# default. Open it up only for an external client of your own:
# CINEFIN_CORS_ORIGINS=https://myapp.example (comma-separated), or
# CINEFIN_CORS_ALL=1 to allow every origin (not recommended).
CORS_ALLOW_ALL_ORIGINS = os.environ.get("CINEFIN_CORS_ALL", "0") == "1"
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.environ.get("CINEFIN_CORS_ORIGINS", "").split(",") if o.strip()]
CORS_ALLOW_CREDENTIALS = False


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Media upload settings
MAX_MEDIA_UPLOAD_SIZE_MB = 5120  # 5GB limit for media uploads
